create table developers (
  id bigint generated by default as identity primary key,
  discord_id bigint UNIQUE NOT NULL,
  discord text NOT NULL,
  position text NOT NULL,
  skills text NOT NULL,
  desired_skills text NOT NULL,
  timezone text NOT NULL,
  twitter text NOT NULL,
  github text NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);