create table public.developers (
  id bigint generated by default as identity primary key,
  discord text NOT NULL,
  discord_id text UNIQUE NOT NULL,
  skills varchar(300) NOT NULL,
  desired_skills varchar(300) NOT NULL,
  timezone varchar(15) NOT NULL,
  twitter varchar(15) NOT NULL,
  github varchar(39) NOT NULL,
  available BOOLEAN NOT NULL DEFAULT FALSE,
  goal varchar (200) DEFAULT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

create table public.invites (
  id bigint generated by default as identity primary key,
  message_id text NOT NULL,
  sender_discord_id text NOT NULL,
  receiver_discord_id text NOT NULL,
  created_at timestamp NOT NULL,
  unique (sender_discord_id, receiver_discord_id),
  constraint fk_sender_discord_id
    foreign key (sender_discord_id)
      references developers(discord_id) on delete cascade,
  constraint fk_receiver_discord_id
    foreign key (receiver_discord_id) 
      references developers(discord_id) on delete cascade
);

alter table public.developers add experience varchar(50);
